language: php

os:
  # - windows
  - linux

php:
  - 8.3
  - 8.4

script:
  - ./vendor/bin/phpunit

before_install:
  - composer self-update

install:
  - composer install --prefer-dist --no-interaction
